version: '2'

services:
  gramine-sdk:
    image: enclaive/gramine-sdk:latest
    container_name: "gramine-sdk"
    build:
      context: .
      dockerfile: ubuntu20.04-gramine-sdk.dockerfile
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      - ./manifest:/manifest      # support manifest editing from host
    ports:
      - '5000:5000'               # add ports for deamons
      - '22:22'                   # ssh
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2    # static IP address throughout development
    stdin_open: true              # docker run -i
    tty: true                     # docker run -t

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1